### ISSUE TITLE
Sichtbarkeit der Einträge

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#10]
Bei der Erstellung eines Termins sollte es die Auswahl zwischen öffentlich und nicht öffentlich geben.
Keins der Werte sollte **default** sein, aber es sollte ein Pflichtfeld sein.

**Comment by Cohen1981** [comment]
Mein Vorschlag wäre eigentlich, das über den Standard Joomla Weg der Zugriffsberechtigung zu machen.
Alles was nicht public ist, ist dann nur für angemeldete Benutzer.

**Comment by Cohen1981** [comment]
Ups. Schließen wollte ich es nicht.

**Comment by KUJensen** [comment]
Funktioniert. Wenn ich die Berechtigung ändere, sieht das nur noch ein angemeldeter User.
