### ISSUE TITLE
Übersicht der Termine, bei denen man angemeldet ist

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#11]
Schön wäre eine Übersicht im Benutzerprofil über die Termine, zu denen man sich angemeldet hat.
Und evtl. die Möglichkeit diese als ICAL zu exportieren.

**Comment by KUJensen** [comment]
Kannst du einen Filter einbinden, sodass nur die Termine angezeigt werden, bei denen man zugesagt hat.
Abgelehnte Veranstaltungen muss ich nicht in der Übersicht sehen.

**Comment by Cohen1981** [comment]
Filter: Alle, Nehme nicht Teil und Teilnahme. Standardfilter auf Veranstaltungen an denen man Teil nimmt.

**Comment by KUJensen** [comment]
Sieht gut aus, wie sieht es mit ICAL Export aus?
Kannst du für jeden AW einen Kalender anlegen, Dann könnte man den verlinken.

**Comment by Cohen1981** [comment]
Habe ich für später auf dem Zettel. Soviele von uns werden das vermutlich eh nicht nutzen.

**Comment by Cohen1981** [comment]
Deine Idee mit dem Kalender für jeden, musst Du mir nochmal erläutern, oder nen Bild malen.

Bin ja für Ideen offen, aber die verstehe ich noch nicht ganz.

**Comment by KUJensen** [comment]
Ich nutze z.B. den Google Kalender und habe in ihm unterschiedliche Kalender verlinkt.
Wenn ich nun die Termine importiere, ist das ganze statisch. Anders wäre das, wenn jeder einen Kalender für sich hat. Dann kann man diesen mit in seinen Kalender integrieren und der würde aktualisiert werden, wenn ein Termin dazu kommt, oder sich ändert. Man könnte auch den Status des Termin mit übernehmen. Dieser Kalender muss im Frontend nicht sichtbar sein. es reicht, wenn er im Backend liegt und auf ihn zugegriffen werden kann. Der ICAL Link darf natürlich auch nur für den jeweiligen AW sichbar sein.
https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=de

**Comment by Cohen1981** [comment]
Ich glaube das Thema Kalender würde ich für eine spätere Version zurückstellen. Die Idee finde ich generell super.

**Comment by Cohen1981** [comment]
Unter diesem Punkt erstmal nur die bereits bestehende ICAL Integration per Mail und Download durchtesten. Kalender schaue ich mir für eine spätere Version an.
Würde jetzt erstmal versuchen eine solide 1.0 hinzustellen.

**Comment by KUJensen** [comment]
Beim Import des Termins kommt folgende Meldung
![grafik](https://user-images.githubusercontent.com/47250562/56805875-9b9a3300-682a-11e9-8850-70a2587e3ca5.png)

**Comment by Cohen1981** [comment]
Was nutz Du für einen Kalender ?

**Comment by KUJensen** [comment]
Den von Google.

**Comment by KUJensen** [comment]
Erster Test war mit der Web Variante

**Comment by KUJensen** [comment]
Import am Smartphone ist i.O.

**Comment by KUJensen** [comment]
Deine ICS Datei
[7_calendar.txt](https://github.com/Cohen1981/yajem/files/3121205/7_calendar.txt)

Meine
[invite.txt](https://github.com/Cohen1981/yajem/files/3121210/invite.txt)

**Comment by Cohen1981** [comment]
Mal meinen Büro Rechner durchforsten. Ich habe mich hier shonmal mit ical beschäftigen müssen und mir schonmal ein abgebrochen das alle Kalender so reagieren, wie ich das möchte.
