### ISSUE TITLE
Kein Geocode möglich

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#13]
Wenn man einen neuen Ort hinzufügen möcht und dann auf Geocode klickt, erscheint folgende Meldung:

**Geocode was not successful for the following reason: ZERO_RESULTS**

Wenn man in die Karte reinzoomt und dann auf Geocode klickt sieht die Meldung so aus:

**Geocode was not successful for the following reason: OVER_QUERY_LIMIT**

**Comment by Cohen1981** [comment]
Jetzt über direkt Aufruf Google Maps umgangen

**Comment by KUJensen** [comment]
Passt!
