### ISSUE TITLE
Termine löschen / archivieren

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#14]
Termine, die nicht mehr benötigt werden, sollen gelöscht oder archiviert werden können.

**Comment by Cohen1981** [comment]
Bislang habe ich es so gelöst, das abgelaufene Termine automatisch ausgeblendet werden. Auf die Art kann man (bislang allerdings nur im Backend) einfach den Termin für das nächste mal anpassen und muss den Rest nicht neu eingeben.

**Comment by KUJensen** [comment]
Kannst du in die Bearbeitung ein Archivieren Button einbauen?
Termine, die keine Teilnehmer finden, oder keine positive Rückmeldung bekommen haben, können damit aus der Liste "gelöscht" werden.

**Comment by Cohen1981** [comment]
Archivieren Button steht jetzt allen angemeldeten Benutzern zur Verfügung.  Wird in der Einzelansicht der Veranstaltung angezeigt.
Sollte ich das Archivieren auf den Organisator einschränken ?
Im Moment kann ein einmal archivierter Eintrag nur aus dem Backend wiederhergestellt werden.
Alternativ könnte ich einen Filter in Übersicht aufnehmen nach archiviert und aktuell ???

Was meinst Du ?

**Comment by KUJensen** [comment]
Ich würde sagen, das der Button erst erscheinen soll, wenn man auf bearbeiten klickt. Das verhindert ein versehentliches Anklicken.
Ist die Frage, ins Archiv, oder nur ein Filter. Hmm. Im Grunde sehe ich das so, wenn ich eine Veranstaltung archiviere, dann darf sie ruhig weg sein. Zur Not legt man sie neu an. Oder hattest du das schon mal, dass du eine Versanstaltung, die abgesagt/abgelehnt wurde, wieder aus der Versenkung holen musstest, weil der Veranstalter sagt, "Kommt doch bitte vorbei!"

**Comment by KUJensen** [comment]
So ist besser
