### ISSUE TITLE
Fehlersymbol"fehlendes Bild" bei Kontakten, wenn kein Bild ausgewählt wurde

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#15]
Wenn man kein Bild vom Anbieter auswählt, wird in der Übersicht das Symbol "fehlendes Bild" angezeigt.
Vorschlag: Standardsymbol, wenn kein Bild vorhanden ist.

z.B. so:
![grafik](https://user-images.githubusercontent.com/47250562/55664635-5c7f5000-5831-11e9-8ddd-c1e7c0133936.png)

oder so was: 
![grafik](https://user-images.githubusercontent.com/47250562/55664611-08746b80-5831-11e9-9cb5-ae3a2952464c.png)

**Comment by KUJensen** [comment]
Kannst du das Bild ein bisschen kleiner machen?

**Comment by Cohen1981** [comment]
Wie viel ist ein bisschen ? ;-)

**Comment by KUJensen** [comment]
50 x 50 px

**Comment by KUJensen** [comment]
sieht gut aus
