### ISSUE TITLE
Neues Profil

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#16]
1. Bitte Festnatz in Festnetz ändern
2. Neuer Gegenstand: Wenn Detail beim Speichern leer ist, erscheint ein Fehler und die Eingabe ist gelöscht.

**Comment by KUJensen** [comment]
Okay, Wenn Detail leer ist, wird es gespeichert.
Jetzt passiert das, wenn man "Art" frei lässt.
Kannst du einfach ein Popup erscheinen lassen, mit dem Hinweis "Bitte Art angeben. z.B. Zelt, o.ä."

**Comment by Cohen1981** [comment]
ist umgesetzt.

**Comment by KUJensen** [comment]
Passt
