### ISSUE TITLE
Veranstaltungen

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#18]
Vorhandene Veranstaltung Cave Gladium:
Beim Anklicken kommt diese Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/47250562/55664791-69517300-5834-11e9-8e0e-5453ba209404.png)

Klick auf neuer Ort:
![grafik](https://user-images.githubusercontent.com/47250562/55664794-838b5100-5834-11e9-82c7-875ed3a0d142.png)

Und der Klick auf Neu:
![grafik](https://user-images.githubusercontent.com/47250562/55664802-9b62d500-5834-11e9-9342-551ad73f2afb.png)

**Comment by Cohen1981** [comment]
Hmm, kann ich so nicht nachvollziehen.... Bitte nochmal versuchen. Kann sein, dass beim hochladen was schief gelaufen war.

**Comment by KUJensen** [comment]
Klappt. Kannst schließen
