### ISSUE TITLE
Ausrüstung

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#19]
Hier könnte noch ein kleiner Hinweis hin, dass die Abspannung in die  Maße mit aufgenommen werden muss.

**Comment by KUJensen** [comment]
Die Auswahl der Ausrüstung im Terminplaner ist leider nicht eindeutig. 
![grafik](https://user-images.githubusercontent.com/47250562/55722888-cbae9d00-5a07-11e9-913d-dc22bffdbd5a.png)
Welches Zelt soll ich nehmen?

**Comment by Cohen1981** [comment]
Dafür hatte ich "Detail" angedacht, aber vermutlich sollte ich die Maße einfach auch noch dranhängen

**Comment by KUJensen** [comment]
Detail wird im Terminplaner nicht angezeigt. Soll ich ein Issue für den Terminplaner aufmachen? ;-)

**Comment by Cohen1981** [comment]
Das Testen dieser Funktion kann erstmal eingestellt werden. Offenbar hab ich einen Trick übersehen mit mehreren gleichzeitig angemeldeten Nutzern umzugehen.
Hatte bislang gedacht Joomla nimmt mir das ab.

**Comment by Cohen1981** [comment]
Noch besser. Wenn man einer Lade Funktion NULL mit gibt bekommt man einfach irgendeinen Satz aus der DB zurück..... Da muss man auch erstmal drauf kommen.
Nu sollte es zuverlässig funktionieren.

**Comment by KUJensen** [comment]
Das sieht doch schon gut aus.
Ich finde aber die Rückmeldung verwirrend.
![grafik](https://user-images.githubusercontent.com/47250562/55773920-3c4ecb80-5a93-11e9-9a30-da72ff474e25.png)
Wäre es für den planer nicht besser, wenn er wüsste, welches Zelt, oder so, mitkommt?

Was hältst du von dieser Idee: Einen Kartenreiter für Platzplanung.
Da kann der Link zur Exceltabelle rein und es kann tabellarisch detailliert aufgeführt werden, wer welche Ausrüstung mitbringt.
Name;Ausrüstung01;Ausrüstung02;Ausrüstung03;Ausrüstung04;Ausrüstung05;Gesamtfläche
Kay;"Zelt Zweimastzelt 8x11";;;;;88m²

**Comment by KUJensen** [comment]
passt
