### ISSUE TITLE
Anmeldung Cave Gladium

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#22]
Hier kann ich mich nicht anmelden.
![grafik](https://user-images.githubusercontent.com/47250562/55719431-7f129400-59fe-11e9-9795-0ffb269b9a34.png)

Bei der von mir angelegten Veranstaltung kann ich mich anmelden.

**Comment by Cohen1981** [comment]
Scheint als müsste ich mir nochmal genau das Joomla Cache verhalten anschauen. Hier scheinen Nutzer Daten und Berechtigungen wild durcheinander gewürfelt zu werden.

**Comment by Cohen1981** [comment]
Mit  #19  erledigt.
