### ISSUE TITLE
Einbindung von der Excel Planungstabelle

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#23]
Mal ein Vorschlag:
Willst du die Excel Planungstabelle als Link mit Einbinden?
Arne fand das Tool super.

Ich werde das auch noch mal überarbeiten und noch eine Hilfeseite machen

**Comment by Cohen1981** [comment]
Habe ich geplant.
Wohin am besten:
1) Im Profil bei der Übersicht über die Organisierten Veranstaltungen
2) An jede Veranstaltung

**Comment by KUJensen** [comment]
Hänge es am besten in jede Veranstaltung. Macht am meisten Sinn

**Comment by KUJensen** [comment]
Ich werde eine Excel Vorlage daraus machen. Mich stört es, dass Änderungen online gespeichert werden. Nach 3 Monaten ist die Größe der Objekte wahrscheinlich verändert, oder etwas ausversehen gelöscht.
Ich teste das gleich und gebe den Link dann durch

**Comment by KUJensen** [comment]
Man möchte sich übergeben. Schreibschutz geht nicht. XLTX Vorlagen kennt Excel Online nicht. Makros gehen auch nicht. 
Ich denke, wir werden doch eher die lokale Excel Variante nehmen müssen.
Ich forsche aber mal weiter.

**Comment by KUJensen** [comment]
Das wars. Ich habe keine gut funktionierende Lösung gefunden,
Bitte die Datei einbinden
[Lagerplanung.xlsx](https://github.com/Cohen1981/yajem/files/3067868/Lagerplanung.xlsx)

Ich schaue aber weiter, ob es noch andere Lösungen gibt

**Comment by KUJensen** [comment]
Weiter mit https://github.com/Cohen1981/yajem/issues/33
