### ISSUE TITLE
Terminplaner - Platzberechnung

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#25]
Das sieht doch schon gut aus.
Ich finde aber die Rückmeldung verwirrend.
![grafik](https://user-images.githubusercontent.com/47250562/55773920-3c4ecb80-5a93-11e9-9a30-da72ff474e25.png)
Wäre es für den Planer nicht besser, wenn er wüsste, welches Zelt, oder so, mitkommt?

Was hältst du von dieser Idee: Einen Kartenreiter für Platzplanung.
Da kann der Link zur Exceltabelle rein und es kann tabellarisch detailliert aufgeführt werden, wer welche Ausrüstung mitbringt.

Name;Ausrüstung01;Ausrüstung02;Ausrüstung03;Ausrüstung04;Ausrüstung05;Gesamtfläche
Kay;"Zelt Zweimastzelt 8x11";;;;;88m²
Halt irgendwie so.

**Comment by Cohen1981** [comment]
Mal ganz generell. Soll die Einzelansicht eines Termins weiterhin als alles auf einmal und man muss scrollen bleiben, oder sollte ich wie bei der Profil Ansicht auf Tabs gehen.?
Hast Du schonmal auf "Benötigter Platz" geklickt ?

**Comment by KUJensen** [comment]
Nein hatte ich noch nicht. War mir nicht klar, dass das geht.
Das mit den Tabs finde ich besser und übersichtlicher

**Comment by KUJensen** [comment]
Ich versuche mal die Planung auf Google Tabs zu ändern.
https://docs.google.com/spreadsheets/d/1Yq0Q7uCnOBTijNtITfaqYsS2aQWpnQlQL3ZDrYBEsXU/edit?usp=sharing
Kannst du so was mit einbinden?

**Comment by KUJensen** [comment]
Das wird nichts. Die Bilder lassen sich nicht drehen.

**Comment by Cohen1981** [comment]
Ich versuche gerade was ganz anderes. (html5 svg)
Hänge auch gerade am drehen, aber das liegt hier definitiv an mir und meinem noch zu oberflächlichen Verständnis.

**Comment by KUJensen** [comment]
Hast du ein Beispiel zum Anschauen?

**Comment by Cohen1981** [comment]
Quick and Dirty Variante mit der ich gerade rumspiele ist jetzt online.
Zu finden in jedem Event unter Platzplaner....
noch komplett rudimentär eingebunden.

**Comment by KUJensen** [comment]
Schau mal hier: https://werner-zenk.de/css/bilder_mit_hover-effekt2.php
Das Glücksrad, evtl kannm an das abwandeln.

**Comment by Cohen1981** [comment]
Habe dieses Thema erstmal zurückgestellt, favorisiere es aber zu: #23 
Ich kümmer mich jetzt erstmal um Mail Benachrichtigungen. Dann sollte zumindest alles da sein, was wir jetzt auch haben.

**Comment by KUJensen** [comment]
Weiter mit https://github.com/Cohen1981/yajem/issues/33
