### ISSUE TITLE
Berechtigungsprobleme

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#26]
Ich mach hier mal das Fass für Berechtigungsprobleme auf.
Also erst mal nicht schließen.

**Comment by KUJensen** [comment]
Die Kontakte sind für nicht angemeldete User sicht bar

**Comment by KUJensen** [comment]
Terminplaner - Platzplaner:
Kannst du auch nicht anklickbar machen? (So wie Kommentare, oder beides ausblenden)

**Comment by Cohen1981** [comment]
Kontakte können über das Backend versteckt werden, wie jeder andere Menüpunkt. Da war ich nur zu faul bei der Testseite.
Terminplaner/ Platzplaner: Habe ich lokal schon umgesetzt. War im Schnellschuss erstmal egal. Nicht erreichbare Tabs werden komplett ausgeblendet.

Aber trotzdem immer weiter, wenn was auffällt.

**Comment by KUJensen** [comment]
Klar und wieder was gefunden: Nicht angemeldete User (NAU) kann sich Profile anzeigen lassen
Terminplanung>z.B. Cave Gladium>Veranstaltung> Organisator AlexB anklicken.

Ich denke, du möchtest deine Adresse nicht online stellen, oder?
![grafik](https://user-images.githubusercontent.com/47250562/55798500-61f9c600-5acf-11e9-8d89-721d5ebf5743.png)

**Comment by KUJensen** [comment]
Das gleiche funktioniert mit dem Veranstalter

**Comment by Cohen1981** [comment]
Für Profile hab ich es gerade verhindert....
Darf der Veranstalter denn nicht von allen gesehen werden ? Eigentlich hinterlegen wir ja keine Infos, die nicht öffentlich zu finden sind ?

**Comment by KUJensen** [comment]
Das ist eine gute Frage. Ich denke, die URL muss reichen. nicht dass die Adresse jemanden stört.
Auch wenn die Daten online ersichtlich sind, verstößt das gegen die DSGVO. Personenbezogene Daten und so.

**Comment by Cohen1981** [comment]
Hmmm. Stimmt auch.

**Comment by Cohen1981** [comment]
Bisher aufgefallene Dinge glatt gezogen.

**Comment by KUJensen** [comment]
Passt alles so weit. Auch Termine, die nicht public sind, sind für NAU nicht sichrbar.
Geklaute Links landen auch im Login.

**Comment by Cohen1981** [comment]
Ich lasse dies Issue mal offen, als Sammelstelle für alles was an Berechtigungen noch so auffällt.

**Comment by KUJensen** [comment]
NAU sieht den Platzplaner
![grafik](https://user-images.githubusercontent.com/47250562/56211070-6a19ae80-6057-11e9-9b4f-1cf16bc664d0.png)

**Comment by Cohen1981** [comment]
Platzplaner für NAU versteckt.
