### ISSUE TITLE
Seitenbreite

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#28]
Wird die Seitenbreite noch an die Breite der Homepage angepasst?

**Comment by Cohen1981** [comment]
Was meinst Du hier genau ?

Ich wollte das ganze so gestalten, das es auf jedem Gerät ansehnlich und bedienbar ist. An diesen Feinschliff bin ich aber noch nicht ran.

**Comment by KUJensen** [comment]
Ich habe die Breiten zwischen dev.survivants-d-acre.com und www.survivants-d-acre.de verglichen, dev ist ein bisschen schmaler

**Comment by Cohen1981** [comment]
:-) Auf Dev ist auch ein anderes Template installiert, welches nur ähnlich aussieht.

**Comment by KUJensen** [comment]
dann ist gut
