### ISSUE TITLE
Mail Benachrichtigung

### ISSUE THREAD

**Issue by Cohen1981** [Cohen1981/yajem#29]
Mail Benachrichtigung bei neuen und geänderten Veranstaltungen.

Benachrichtigungen sollen einmal global ein/ ausgeschaltet werden (für neu und geändert getrennt)
und zum anderen von jedem User einzeln im Profil.

Zusätzlich gibt es die Möglichkeit unabhängig von der Profil Einstellung sich für jede Veranstaltung einzeln für Benachrichtigungen zu registrieren. Dies geschieht unter dem Tab "Teilnehmer"

**Comment by Cohen1981** [comment]
Jetzt Online. Globaler Standard. Bei neuen Veranstaltungen werden Mails versand, bei geänderten nicht.

**Comment by KUJensen** [comment]
Wie sieht es aus mit abgesagten Veranstaltungen? Kommt dann eine Absagemail?

**Comment by KUJensen** [comment]
Neuen Termin angelegt:
![grafik](https://user-images.githubusercontent.com/47250562/56014850-30fbda00-5cf7-11e9-8427-05d92bcccdd1.png)

**Comment by KUJensen** [comment]
Termin angenommen, keine Mail

**Comment by Cohen1981** [comment]
Termin Annahme habe ich tatsächlich noch nicht umgesetzt. Neuer Termin ist merkwürdig... Sollte wohl Mal kontrollieren ob die Seite überhaupt Mails verschicken kann.

**Comment by Cohen1981** [comment]
Mails werden jetzt versand.
Bei neuer Veranstaltung pauschal an alle, die nicht expliziet im Profil gesagt haben "keine Mails bei neu".
Bei geänderter Veranstaltung an alle, die "bei Änderung" im Profil aktiviert haben, oder einzeln "abboniert".
Bei Status Änderung der Veranstaltung an alle Teilnehmer.
Bei An- und Ab-Meldung an den Teilnehmer.

**Comment by Cohen1981** [comment]
Brauchen wir eigentlich eine Mail Benachrichtigung bei neuen Kommentaren an einer Veranstaltung ?

**Comment by KUJensen** [comment]
Grundsätzlich ist die Mailbenachrichtigung bei Kommentaren eher verwirrend.
Evtl. ein Vorschlag, wie man das händeln könnte.
Für den Fall, das einer einen wichtigen Kommentar abgeben möchte, den alle Teilnehmer lesen sollen, könnte man eine Checkbox 'wichtig' einbauen. Nur diese Kommentare würden dann benachrichtigen.

**Comment by Cohen1981** [comment]
Mail Benachrichtigung bei Kommentaren ist abgewählt. Dafür gibt es die "wichtig" Checkbox bei der Terminänderung.
