### ISSUE TITLE
Neuer Termin und dann neuer Ort - Eingabe wird verworfen

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#31]
Wenn man einen neuen Termin anlegt und dann feststellt "Oh, ich muss den Ort noch erstellen", dann ist nach dem Speichern des Ortes, die Eingabe der Termins verworfen.

**Comment by KUJensen** [comment]
Neuer Termin und dann neuen Ort eingegeben. Auf Speichern & Schließen geklickt.
Neuer Ort wird nicht geschlossen, sondern die Eingabe für einen neuen Ort angeboten.
Mit Abbrechen gelange ich wieder in die Übersicht 'Termine'

**Comment by Cohen1981** [comment]
Bist Du sicher, da Du Dich da nicht verguckt hast ? Bei mir klappt das. Kann natürlich sein, das eins meiner Zwischenupdates das kurzfristig zerschossen hatte.

**Comment by KUJensen** [comment]
Lag wohl am Zwischenupdate. Jetzt gehts wieder
