### ISSUE TITLE
Termine - Erweiterter Status

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#32]
Wir sollten die Stati für die Termine erweitern:
"Kreis blau" - Interesse sammeln
"Kreis orange" - Anmeldung abgeschickt
"Kreis grün" - Termin bestätigt
"Kreis rot" - Termin abgesagt/negative Rückmeldung (evtl. automatische Archivierung nach 30 Tagen?)

Für den Fall, dass jeder seinen Kalender hat: Den Termin in der entsprechenden Farbe darstellen.

**Comment by Cohen1981** [comment]
Automatische Archivierung folgt.

**Comment by KUJensen** [comment]
Der Ampelstatus ist gut!
