### ISSUE TITLE
Tool zur Lagerplanung

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#33]
Lass uns mal alles zum "Tool zur Lagerplanung" hier sammeln

**Comment by KUJensen** [comment]
- Der Verschiebemodus ist mit dem FF nicht nutzbar.
- Das zu verschiebene Objekt bleibt an anderen Objekten hängen
- Die Objekte werden untereinander angezeigt und bei zu vielen Objekten verschwindet einiges unten
- Die Skalierung passt nicht
- Die Drehbuttons bitte bei Nichtgebrauch ausblenden
- Das Gleiche für die Namen
- Ich erstelle die Bilder ohne Namen noch einmal neu

**Comment by KUJensen** [comment]
- Das Planfeld darf gerne größer sein
- die Objekte dürfen auch gerne größer sein

**Comment by KUJensen** [comment]
Kannst du den Stand der Planung speichern, sodaß jeder den Plan einsehen kann?
So was kann hilfreich sein, wenn man zuerst auf dem Plane steht und sich fragt, wie man anfangen soll.
Klar, auf einigen Märkten ergibt es sich erst dann, wenn man vor Ort ist.

**Comment by Cohen1981** [comment]
Habe ich generell vor.

**Comment by KUJensen** [comment]
Hier die neuen Bilder
[pics.zip](https://github.com/Cohen1981/yajem/files/3115514/pics.zip)

**Comment by Cohen1981** [comment]
Schau ich mir mal an.

**Comment by KUJensen** [comment]
Ich sehe gereade, da fehlt noch was. Packe ich gleich dazu

**Comment by KUJensen** [comment]
[pics.zip](https://github.com/Cohen1981/yajem/files/3115728/pics.zip)
Sind die SVG Dateien so in Ordnung?

**Comment by KUJensen** [comment]
Wo legst du die Bilder ab? Am besten wäre es in einem eigenen Odner.

**Comment by Cohen1981** [comment]
Stimmt. Habe aber noch keinen angelegt. Fürs testen egal, aber für live gang lege ich noch ein fest.

**Comment by KUJensen** [comment]
Okay, ich wollte die Ausrüstung neu zuordnen und suche die Bilder

**Comment by Cohen1981** [comment]
Die habe ich in einem Ordner hochgeladen, den man über den Media Manager offenbar nicht erreicht und per SQL gesetzt

**Comment by Cohen1981** [comment]
OK. Ich denke wir bleiben erstmal bei "normalen" Bild Dateien. Wäre zwar schön mit SVG, aber mangels Unterstützung im Joomla Core, wäre der Aufwand hier zu groß.

**Comment by KUJensen** [comment]
Kannst du denn einen Ordner anlegen, damit ich an die Bilder komme?

**Comment by Cohen1981** [comment]
Habe einen Ordner Ausruestung angelegt und schonmal einige Bilder hochgeladen

**Comment by KUJensen** [comment]
Super, kannst du den Ordner auch gleich als Plfad vorwählen?

**Comment by Cohen1981** [comment]
Ist schon vorbereitet. Mach nur noch ein paar andere Kleinigkeiten fertig.

**Comment by KUJensen** [comment]
Jetzt, wo keine Namen mehr auf Zelten stehen, sind einige Gegenstände schwer zu identifizieren. Ein Beschreibungsfeld zu dem Gegenstand wäre da nicht schlecht. Sonst findet Winnie sein Zelt nicht ;-)

**Comment by KUJensen** [comment]
Mal was grundsätzliches zu den 'Speichern' Buttons. Macht es Sinn ein Button für 'Speichern', einen für 'Speichern und schließen' und einen für 'Speichern und neu'.
'Speichern' und 'Speichern und schließen' kannst du zusammenfasssen. Das verwirrt nur. Ich klicke grundsätzlich auf 'Speichern', will aber Speichern und schließen.

**Comment by Cohen1981** [comment]
Da habe ich mich bislang einfach an den Standard gehalten. Ich hänge nicht am Speichern Button. Kann ich also raus nehmen. 
Beschreibungsfeld füge ich hinzu. Sehe was Du meinst.

**Comment by Cohen1981** [comment]
Beschreibung ist jetzt Online. Du meintest für eine Anzeige in der Bild Auswahl im Profil, oder ?

**Comment by KUJensen** [comment]
Du meinst den Pfad? Ich würde sagen, so wie es jetzt ist, ist gut. Die Belder werden bei der Bildauswahl angezeigt.

**Comment by Cohen1981** [comment]
Nutzt Du eigentlich bearbeiten, oder löscht Du die alten Bilder und legst neu an ?

**Comment by KUJensen** [comment]
Bearbeiten habe ich zu spät gesehen. Der war vorhin noch nicht da, oder?

**Comment by Cohen1981** [comment]
Doch... :-D Vielleicht sollte ich in der Ansicht bearbeiten und neu in der Reihenfolge tauschen....

**Comment by Cohen1981** [comment]
Plan lässt sich jetzt als SVG oder PNG (Noch nicht ganz hübsch) speichern.
Mal sehen ob ich einen gespeicherten Stand auch nutzen kann um weiter Anmeldungen rein zu rendern und nicht jedesmal neu anfangen zu müssen.

**Comment by KUJensen** [comment]
Moin, beim SVG Speichern passiert nichts. Ich sehe nur da Laden Symbol
Ich kann mich nicht mehr von Veranstaltungen wieder abmelden.
Im Planungstool sehe ich nur grüne Platzhalter

**Comment by Cohen1981** [comment]
An den Platzhaltern bist Du selbst Schuld. ;-) Wenn ich Maße aber kein Bild finde (z.B. weil es gelöscht wurde) zeige ich einen Platzhalter.
Das Abmelden liegt wohl am abgelaufenen Anmeldeschluß. Änder ich so, das Abmelden immer möglich ist und ein Hinweis erscheint, das der Anmeldeschluß abgelaufen ist.
Download svg: Du nutzt FF, oder ? Habe ich auch schon festgestellt, dass der wieder zickt.

**Comment by KUJensen** [comment]
Stimmt, Die Bilder haben ja neue Namen...
Ja, ich nutze den FF. Bei der DNP ist Chrome verboten.

**Comment by Cohen1981** [comment]
Na dann habe ich ja den perfekten Tester. Lokal bei mir geht der Download jetzt. Ziehe nur noch kurz die Installations Skripte glatt und lade dann den Stand erstmal hoch.

**Comment by Cohen1981** [comment]
Korrekturen Online.

**Comment by KUJensen** [comment]
Okay, abmedlen geht, aber anmelden nicht mehr. Ist jetzt auch nicht so schlim. Meldung bis, bedeutet nicht Anmeldeschluss am. Das ist schon ein Unterschied.

**Comment by Cohen1981** [comment]
Hmmm, dann scheint PHP eine eigene Interpretation von <= bei Datums Angaben zu haben. Schau ich mir nochmal an.

**Comment by KUJensen** [comment]
sonst setze doch als default 23:59:59. Muss ja nicht angezeigt werden

**Comment by KUJensen** [comment]
Downoad SVG geht jetzt, sieht aber so aus:
![grafik](https://user-images.githubusercontent.com/47250562/56790802-d2aa1d80-6805-11e9-8d23-9a00f7daab0f.png)

**Comment by Cohen1981** [comment]
Korrektur shon vorbereitet. Hatte übersehen, das ich bislang die Uhrzeit mit berücksichtige. Jetzt vergleiche ich nur noch das Datum.

**Comment by Cohen1981** [comment]
Das sind die Platzhalter. Werden mit dem nächsten Update auch gespeichert.
Angeblich soll man zwar css mit exportieren können, aber praktisch muss das styling offenbar am Element hängen.

**Comment by Cohen1981** [comment]
So. Noch ein paar Korrekturen und Aufhübschungen. Ich werde jetzt mal die Winnie Brille aufsetzen und schauen, wo ich Texte und/ oder Layout anpassen sollte, damit auch Winnie damit klar kommt. ;-)

**Comment by KUJensen** [comment]
Export als PNG funzt nicht.
![planing](https://user-images.githubusercontent.com/47250562/56806756-24b26980-682d-11e9-927c-ca4f7630f5cc.png)

**Comment by KUJensen** [comment]
Ähhh, da sollte ein Bild als Anhang sein...

**Comment by Cohen1981** [comment]
Untersuch mal den Kommentar. Da ist auch ein Bild. ;-) Allerdings komplett transparent.

**Comment by Cohen1981** [comment]
Toll, den Part nicht angefasst, aber kaputt. Sowas liebe ich. :-(

**Comment by Cohen1981** [comment]
Export als PNG geht zwar immer noch nicht. Dafür kann man jetzt den Planungs Zwischenstand speichern.

**Comment by KUJensen** [comment]
Moin, werde ich morgen früh mal durchtesten.

**Comment by Cohen1981** [comment]
Durch Zufall über ein Posting gestolpert, welches die Lösung für den PNG Export brachte.

**Comment by KUJensen** [comment]
Kannst du bei Tankumsee mal schauen, ob es so aussieht und dann mache mal Änderungen
![grafik](https://user-images.githubusercontent.com/47250562/57069738-c0ccec80-6cd5-11e9-91c6-4763962c7ef8.png)

**Comment by Cohen1981** [comment]
Geändert:
![image](https://user-images.githubusercontent.com/26430338/57070116-c0812100-6cd6-11e9-8f80-56822114be62.png)

**Comment by KUJensen** [comment]
Super, kann ich auch sehen

**Comment by KUJensen** [comment]
Hab noch ein Problem gefunden:
Der Stand ist gespeichert.
Ich habe noch Schutzausrüstung und Lagerausstattung hinzugefügt.
Das wird aber nicht angezeigt.
Wenn ich mich von Tankumsee abmelde, werden meine Gegenstände weiter angezeigt.

**Comment by Cohen1981** [comment]
Den Fall Abmelden hatte ich nicht bedacht. Was gespeichert ist, wird einfach wieder ausgegeben. Gehe ich ran

**Comment by KUJensen** [comment]
Der Name wird unter dem Objekt bei 'mouse over' eingeblendet, aber nicht wieder ausgeblendet.

**Comment by Cohen1981** [comment]
Vorbereitet, noch nicht online !

- Abmelden entfernt jetzt die Ausrüstung aus dem Zwischengespeicherten Stand.
- Texte werden ausgeblendet.

Durch den Umbau werden beim hochladen die bisherigen Zwischenstände einmal gelöscht !

**Comment by Cohen1981** [comment]
Jetzt Online.

**Comment by KUJensen** [comment]
Das funzt

**Comment by Cohen1981** [comment]
Gestern noch festgestellt, dass das Planungstool nicht funktioniert wenn sich ein User ab-/ an-meldet.
Korrektur ist bereits Online. Bitte nochmal anschauen.

**Comment by Cohen1981** [comment]
Drehen ist gerade kaputt. Ich schau nochmal drauf. Habe ich wohl beim Umbau etwas zu viel gelöscht.

**Comment by Cohen1981** [comment]
Fixed.
