### ISSUE TITLE
Veranstaltungsorte

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#34]
Baue doch bitte bei den Veranstaltungsorten ein Feld ein, wo man die GPS Koordinaten (optional) angeben kann. (z.B. 52.834031, 10.683169)
Manchmal ist die Adresse nicht ausreichend, um den Ort wirklich zu finden.

**Comment by Cohen1981** [comment]
Mach ich.

**Comment by Cohen1981** [comment]
Koordinaten sind drin.
Ich bin gerade dabei, eine Übersicht über die Orte aufzubauen analog der Veranstaltungen.
Könnte mir vorstellen, das doch mal der ein oder andere Ort nach bearbeitet werden soll.
