### ISSUE TITLE
Kategorien Gegenstände im Lager

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#35]
Die Kategorien sollten wir neu einteilen

1. Zelte
2. Sonnensegel / Lagerplane
   - grüne Plane
3. Lagerausstattung
   - Tisch
   - Bank
   - Altar
   - Bliede
4. Schutzausrüstung
   - Feuerlöscher
   - Erste Hilfe Set
5. Generelle Gruppenausrüstung
   - Sonnensegel 5x5
   - Feuerstelle
   - Waffenständer

Bänke und Tische müssen natürlich nicht auf dem Plan erscheinen, ist nur gut zu wissen, wer was mitnimmt.
Die Schutzausrüstung sollte dann im jeweiligen Zelt erscheinen. z.B. rotes Kreuz und rotes F

**Comment by Cohen1981** [comment]
Kannst Du generell bereits unter "Ausrüstungstypen" vorbereiten.
Nur für die Anzeige der Erste Hilfe Ausrüstung muss ich dann tatsächlich noch Anpassungen vornehmen.

**Comment by KUJensen** [comment]
Wie ordne ich denn Gegenständen der Gruppe zu?

**Comment by Cohen1981** [comment]
In die Gruppe - bearbeiten und dann unter Ausrüstung.

**Comment by KUJensen** [comment]
Gefunden, kann aber nichts ändern
![grafik](https://user-images.githubusercontent.com/47250562/57065154-dc7dc600-6cc8-11e9-993f-3600cde37923.png)

**Comment by Cohen1981** [comment]
Uups. Falsche Berechtigungsprüfung. Sollte jetzt gehen.

**Comment by KUJensen** [comment]
jetzt gehts

**Comment by KUJensen** [comment]
Doch noch was gefunden. Ich kann Survivants keine 'Lagerausstattung' verpassen. Ist leer.
![grafik](https://user-images.githubusercontent.com/47250562/57069989-6a13e280-6cd6-11e9-9546-fd3a6d94b9cb.png)

**Comment by Cohen1981** [comment]
Das liegt daran, das bei dem Typ Lagerausstattung keine Längen und Breiten Angaben zulässig sind.
Momentan mach ich an der Option fest, ob das Ausrüstung zum Anzeigen im Planungstool ist, oder nicht.
Sollte vielleicht gar nicht erst de Möglichkeit bieten, für so einen Typ Bilder zu hinterlegen.

**Comment by KUJensen** [comment]
Okay, Lagerfeuer und Waffenständer haben Maße. Ich ändere das mal.

**Comment by KUJensen** [comment]
Hmm, dann wird die Schutzausrüstung auch nicht angezeigt.

**Comment by KUJensen** [comment]
![grafik](https://user-images.githubusercontent.com/47250562/57070676-739e4a00-6cd8-11e9-9b70-bd3222e54640.png)


Die Felder sind im 'nicht bearbeiten' Modus nicht gesperrt und können geändert werden, was aber keine Auswirkung hat.

**Comment by KUJensen** [comment]
Ist geändert, aber ich kann die Gegenstände nicht anpassen.
![grafik](https://user-images.githubusercontent.com/47250562/57070889-1656c880-6cd9-11e9-8ff2-5a1ae49375f0.png)

Die Maße kann ich nicht angeben
![grafik](https://user-images.githubusercontent.com/47250562/57070924-29699880-6cd9-11e9-9a2a-c4aa50475dcb.png)

Auch bei Neuanlage nicht.

**Comment by Cohen1981** [comment]
So isses. Ich überlege noch, wie ich das am besten umbaue.

Meine Idee bisher:
Ausrüstungstypen:
- "hat Länge und Breite" umbenennen in, Anzeige im Planungstool
Bei den Ausrüstungsbildern:
- Eine Option "Anzeige als Symbol", die wenn ausgewählt ein Erfassen von festen Maßen fürs Bild ermöglicht und ein Ändern dieser Maße beim Erfassen als Ausrüstungsgegenstand verhindert.

**Comment by Cohen1981** [comment]
Bislang werden Maße erst bei der Erfassung als Ausrüstungsgegenstand erfasst.

**Comment by Cohen1981** [comment]
Ich glaube der Weg ist richtig, aber die Umsetzung braucht noch Feinschliff.

**Comment by KUJensen** [comment]
'Im Planungstool anzeigen' finde ich gut.
Ich denke die Größe der Gegenstände spielt keine Rolle bei der Berechnung der Fläche.

**Comment by KUJensen** [comment]
Wollen wir evtl die Maße mit und auch ohne Abspannung mit aufnehmen?
(Haben wir schon mal gemacht)

**Comment by KUJensen** [comment]
> 
> 
> Bislang werden Maße erst bei der Erfassung als Ausrüstungsgegenstand erfasst.

Genau das geht nicht

**Comment by KUJensen** [comment]
Okay, verstanden. Geht doch

**Comment by KUJensen** [comment]
Jetzt wollte ich ein Lagergegenstand bei Survivants aufnehmen. Ich kann aber kein Bild auswählen.
![grafik](https://user-images.githubusercontent.com/47250562/57072499-350b8e00-6cde-11e9-969e-c3aaa52fd908.png)

**Comment by Cohen1981** [comment]
Für die Kategorie gibt es auch noch keine Bilder. ;-)

Die Idee war, das Bilder nicht von jeden hochgeladen werden, sondern nur von Admins. Deswegen der Extra Menüpunkt. Die Maße kennt aber der Besitzer selbst am Besten. Deswegen erst bei der konkreten Ausrüstung.
Ich gebe zu, ist noch nicht perfekt. Bin für Ideen dankbar.

**Comment by Cohen1981** [comment]
Mal laut gedacht. Wofür wollen wir Schutzausrüstung im Lagerplan anzeigen ?
Bisher hat das noch keinen Veranstalter interessiert. 
Ich würde eher noch eine zusätzliche Liste (informativ) in der Lasche Platzplaner einblenden, wo alle Ausrüstungsgegenstände aufgelistet werden, die mitgebracht werden, aber kein Bild haben.
