### ISSUE TITLE
Fehler bei neuer Termin / Termin bearbeiten

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#37]
Wenn man einen Termin anlegt oder bearbeitet und dann auf 'speichern und schließen' klickt kommt folgende Meldung. Gespeichert wird aber trotzdem.
![grafik](https://user-images.githubusercontent.com/47250562/57004147-cab6f880-6bcc-11e9-8783-642a695b324f.png)

'Zurück' und 'Abbrechen' erzeugt auch diesen Fehler

**Comment by KUJensen** [comment]
![grafik](https://user-images.githubusercontent.com/47250562/57004180-271a1800-6bcd-11e9-9970-c9205a5d2bc6.png)
Man könnte meinen, dass man hier eine URL zu einem Bild angeben könnte.

**Comment by Cohen1981** [comment]
Leider lässt sich das Eingabefeld nicht ausblenden. Scheint ein nicht besonders gut unterstütztes Feature von Joomla zu sein.

**Comment by KUJensen** [comment]
Schade. Wollen wir denn Bilder von extern mit einbinden, oder lieber nicht?

**Comment by Cohen1981** [comment]
Der Witz ist. Mir ist es bisher noch nicht mal gelungen eine eingegebene URL zu übernehmen.
Suche gerade nach einer nachhaltigen Möglichkeit das Feld doch los zu werden. Externe Bilder möchte ich eigentlich nicht nutzen.

**Comment by KUJensen** [comment]
ist in Ordnung.

hidden geht nicht?

**Comment by Cohen1981** [comment]
Das ganze Auswahl Fenster kommt aus dem Joomla Core. Änder ich es dort, wird es mit dem nächsten Joomla Update überschrieben. :-(
Zwar bietet Joomla template overrides an, für solche Fälle.... Die gelten aber wieder nicht für PopUp Fenster.
Ist gerade zum Mäuse melken.

**Comment by KUJensen** [comment]
Ist zwar doof, aber webb es nicht anders geht...

Kann zu
