### ISSUE TITLE
Fehler bei neues Ausrüstungsbild / bearbeiten

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#38]
'Speichern und Neu' erzeugt folgenden Fehler
![grafik](https://user-images.githubusercontent.com/47250562/57004389-f63ae280-6bce-11e9-9416-df545dcf289f.png)

**Comment by Cohen1981** [comment]
Fixed.

**Comment by KUJensen** [comment]
Geht jetzt
