### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#39]
Hier sammeln wir die Ideen und Gedanken, die uns so in den Kopf schießen und können darüber diskutieren.

**Comment by KUJensen** [comment]
**Anmeldung zum Termin**
- jeder sollte die Möglichkeit haben, Ausrüstung nachträglich hinzuzufügen, oder wieder zu entfernen.

**Profil > Ausrüstung**
- Es wäre toll, wenn man Ausrüstungsgegenstände aus Standard definieren kann. sollten aber im Termin trotzdem abwählbar sein

**Termin > Übersicht mitgebrachten Ausrüstung**
- Eine Übersicht, wer was mitbringt. (ohne Bilder) 
    Einfach, um eine Entscheidungshilfe zu haben, ob man dieses oder jenes noch benötigt

**Gegenstände für die Planung**
- Alle Gegenstände sollten mit Bild möglich sein
- Größenangabe in 0,1m Schritten
- Checkbox: für Planungstool relevant

**Planungstool**
- Resetbutton für das Planungstool
- Zoommöglichkeit

Das war es für den Anfang

**Comment by Cohen1981** [comment]
Anmeldung zum Termin

jeder sollte die Möglichkeit haben, Ausrüstung nachträglich hinzuzufügen, oder wieder zu entfernen.
Profil > Ausrüstung

_Kann man doch schon ?! Oder meinst Du im Termin ?_

Es wäre toll, wenn man Ausrüstungsgegenstände aus Standard definieren kann. sollten aber im Termin trotzdem abwählbar sein
Termin > Übersicht mitgebrachten Ausrüstung

_Guter Punkt. #40 _

Eine Übersicht, wer was mitbringt. (ohne Bilder)
Einfach, um eine Entscheidungshilfe zu haben, ob man dieses oder jenes noch benötigt
Gegenstände für die Planung

_Seit dem letzten Update unterhalb der Planungsfläche._

Alle Gegenstände sollten mit Bild möglich sein

_Seit dem letzten Update bereits möglich_

Größenangabe in 0,1m Schritten   _#41_
Checkbox: für Planungstool relevant _Wo und soll was genau bewirken ?_
Planungstool

Resetbutton für das Planungstool

_Resetet dann nur die Planungsfläche und nicht die gespeicherten Zwischenstände, oder ?_

Zoommöglichkeit

_Ich glaube Du brauchst ne Brille. ;-) Habe ich aber für mich in der langfrist Planung._

**Comment by KUJensen** [comment]
_Anmeldung zum Termin

jeder sollte die Möglichkeit haben, Ausrüstung nachträglich hinzuzufügen, oder wieder zu entfernen.
Profil > Ausrüstung

Kann man doch schon ?! Oder meinst Du im Termin ?_
**Ja, im Termin.** 

_Größenangabe in 0,1m Schritten #41
Checkbox: für Planungstool relevant Wo und soll was genau bewirken ?_

**Na ja, war jetzt so gedacht, das was checked ist wird im Planungstool angezeigt, sofern es mitkommt.
Das was unchecked ist, erscheint dann nur auf der Liste**

_Zoommöglichkeit

Ich glaube Du brauchst ne Brille. ;-) Habe ich aber für mich in der langfrist Planung._

**Du rückst deine ja nicht raus ;-)**

**Comment by Cohen1981** [comment]
Anmeldung zum Termin:
jeder sollte die Möglichkeit haben, Ausrüstung nachträglich hinzuzufügen, oder wieder zu entfernen.

_Hier würde ich erstmal beobachten ob das wirklich notwendig ist. Im Zweifel muss man sih halt noch einmal ab- und wieder an- melden._

Checkbox: für Planungstool relevant

_Soll das dann jeder selbst entscheiden können ? Dann würde ich die bisherige Festlegung in den Ausrüstungstypen wieder rück bauen. Hätte gedacht das es so einfacher ist (denke dabei an Winnie)_

**Comment by KUJensen** [comment]
Ne, die Checkbox wäre dann bei neuen Gegenstände, die wir, die Admins, aufnehmen.
Sagen wir mal Tische und Bänke. Da ist es interessant wie viele da sind. Die müssen aber nicht auf dem Tool auftauchen. Oder woran willst du das festmachen, was angezeigt wird und was nicht?

**Comment by Cohen1981** [comment]
Bislang an dem Feld im Ausrüstungstyp:
![image](https://user-images.githubusercontent.com/26430338/57208498-6df47d00-6fd4-11e9-8ca2-aa82d34656d9.png)

Um es dem Rest einfacher zu machen, habe ich die Anzeige bei der Erfassung von Ausrüstung etwas angepasst:
![image](https://user-images.githubusercontent.com/26430338/57208538-97150d80-6fd4-11e9-9ba5-5ff3d03e8769.png)

Diese neue Version geht auch demnächst Online.

**Comment by KUJensen** [comment]
Okay. passt

**Comment by Cohen1981** [comment]
Wenn uns was neues einfällt, sollten wir lieber auch einen neues Ticket öffnen.
