### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#44]
Wenn man sich in die Termine klickt und dann feststellt, man ist nicht angemeldet und sich dann anmeldet, springt er nach der Anmeldung wieder auf Home.
Kannst du das so ändern, das er auf die letzte Seite geht?

**Comment by Cohen1981** [comment]
Erledigt. Das war nur eine Einstellung, die ich schon ewig vornehmen wollte und immer wieder vergessen habe. :-/
