### ISSUE TITLE
Planungstool - zeigt zu viel an

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#45]
![grafik](https://user-images.githubusercontent.com/47250562/75110039-3ae5ad80-5629-11ea-9d9f-3f4cb96c15ad.png)
![grafik](https://user-images.githubusercontent.com/47250562/75110046-52bd3180-5629-11ea-96f4-c8e37099b79d.png)
Die, die sich abgemeldet haben, sind in der Planung vorhanden. Arne ist sogar 2x "nicht" dabei.

**Comment by Cohen1981** [comment]
Neues Auftraten der Problematik verhindert. Muss nur noch aufräumen
