### ISSUE TITLE
Status der Anmeldung

### ISSUE THREAD

**Issue by KUJensen** [Cohen1981/yajem#46]
Ich vermisse "Anmeldung abgeschickt"

![grafik](https://user-images.githubusercontent.com/47250562/75110610-818ad600-5630-11ea-8e5d-5f2c3a919fe1.png)

**Comment by Cohen1981** [comment]
Wieso brauchst Du den Status beim Einstellen eines Termins ? Wenn der Erstellt ist, kann der Organisator den Status auch so umsetzen.
![image](https://user-images.githubusercontent.com/26430338/75251157-57751780-57da-11ea-9db0-751505d7b6c4.png)

**Comment by KUJensen** [comment]
Da war der Fehler. Ich habe die Termine eingetragen und Alex als Organisator eingetragen.
Gut, ändere ich auf mich
