### ISSUE TITLE
"Hilfstext" im Kommentar Feld verschwindet nicht

### ISSUE THREAD

**Issue by Cohen1981** [Cohen1981/yajem#7]
**Describe the bug**
"Hilfstext" im Kommentar Feld verschwindet nicht

**To Reproduce**
1. Klicke ins Kommentar Feld bei einer Veranstaltung und fange an zu tippen

**Expected behavior**
Hilfstext wird ersetzt.

**Comment by Cohen1981** [comment]
Hilfstext wird komplett weg gelassen

**Comment by KUJensen** [comment]
Das Kommentarfeld ist sauber.
